-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Enum.AccountType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type AccountType
    = Credit
    | Debit


list : List AccountType
list =
    [ Credit, Debit ]


decoder : Decoder AccountType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREDIT" ->
                        Decode.succeed Credit

                    "DEBIT" ->
                        Decode.succeed Debit

                    _ ->
                        Decode.fail ("Invalid AccountType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : AccountType -> String
toString enum =
    case enum of
        Credit ->
            "CREDIT"

        Debit ->
            "DEBIT"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe AccountType
fromString enumString =
    case enumString of
        "CREDIT" ->
            Just Credit

        "DEBIT" ->
            Just Debit

        _ ->
            Nothing
