-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.Account exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.Enum.AccountType
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


amount : SelectionSet String MonisApp.Object.Account
amount =
    Object.selectionForField "String" "amount" [] Decode.string


currency : SelectionSet String MonisApp.Object.Account
currency =
    Object.selectionForField "String" "currency" [] Decode.string


icon : SelectionSet (Maybe String) MonisApp.Object.Account
icon =
    Object.selectionForField "(Maybe String)" "icon" [] (Decode.string |> Decode.nullable)


{-| The ID of an object
-}
id : SelectionSet MonisApp.ScalarCodecs.Id MonisApp.Object.Account
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecId |> .decoder)


isActive : SelectionSet Bool MonisApp.Object.Account
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


name : SelectionSet String MonisApp.Object.Account
name =
    Object.selectionForField "String" "name" [] Decode.string


transactions :
    SelectionSet decodesTo MonisApp.Object.Transaction
    -> SelectionSet (List decodesTo) MonisApp.Object.Account
transactions object_ =
    Object.selectionForCompositeField "transactions" [] object_ (identity >> Decode.list)


type_ : SelectionSet MonisApp.Enum.AccountType.AccountType MonisApp.Object.Account
type_ =
    Object.selectionForField "Enum.AccountType.AccountType" "type" [] MonisApp.Enum.AccountType.decoder


user :
    SelectionSet decodesTo MonisApp.Object.User
    -> SelectionSet decodesTo MonisApp.Object.Account
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
