-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.Category exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.Enum.CategoryType
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


icon : SelectionSet String MonisApp.Object.Category
icon =
    Object.selectionForField "String" "icon" [] Decode.string


{-| The ID of an object
-}
id : SelectionSet MonisApp.ScalarCodecs.Id MonisApp.Object.Category
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String MonisApp.Object.Category
name =
    Object.selectionForField "String" "name" [] Decode.string


type_ : SelectionSet MonisApp.Enum.CategoryType.CategoryType MonisApp.Object.Category
type_ =
    Object.selectionForField "Enum.CategoryType.CategoryType" "type" [] MonisApp.Enum.CategoryType.decoder
