-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.LoginResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


token : SelectionSet String MonisApp.Object.LoginResult
token =
    Object.selectionForField "String" "token" [] Decode.string


user :
    SelectionSet decodesTo MonisApp.Object.User
    -> SelectionSet decodesTo MonisApp.Object.LoginResult
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
