-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.Transactions exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


{-| An object relationship
-}
account :
    SelectionSet decodesTo MonisApp.Object.Accounts
    -> SelectionSet decodesTo MonisApp.Object.Transactions
account object____ =
    Object.selectionForCompositeField "account" [] object____ Basics.identity


account_id : SelectionSet MonisApp.ScalarCodecs.Uuid MonisApp.Object.Transactions
account_id =
    Object.selectionForField "ScalarCodecs.Uuid" "account_id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


amount : SelectionSet Int MonisApp.Object.Transactions
amount =
    Object.selectionForField "Int" "amount" [] Decode.int


{-| An object relationship
-}
category :
    SelectionSet decodesTo MonisApp.Object.Categories
    -> SelectionSet decodesTo MonisApp.Object.Transactions
category object____ =
    Object.selectionForCompositeField "category" [] object____ Basics.identity


category_id : SelectionSet MonisApp.ScalarCodecs.Uuid MonisApp.Object.Transactions
category_id =
    Object.selectionForField "ScalarCodecs.Uuid" "category_id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


comment : SelectionSet (Maybe String) MonisApp.Object.Transactions
comment =
    Object.selectionForField "(Maybe String)" "comment" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet MonisApp.ScalarCodecs.Timestamptz MonisApp.Object.Transactions
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


date : SelectionSet MonisApp.ScalarCodecs.Timestamptz MonisApp.Object.Transactions
date =
    Object.selectionForField "ScalarCodecs.Timestamptz" "date" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


deleted : SelectionSet Bool MonisApp.Object.Transactions
deleted =
    Object.selectionForField "Bool" "deleted" [] Decode.bool


id : SelectionSet MonisApp.ScalarCodecs.Uuid MonisApp.Object.Transactions
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


operation : SelectionSet String MonisApp.Object.Transactions
operation =
    Object.selectionForField "String" "operation" [] Decode.string


payee : SelectionSet String MonisApp.Object.Transactions
payee =
    Object.selectionForField "String" "payee" [] Decode.string


updated_at : SelectionSet MonisApp.ScalarCodecs.Timestamptz MonisApp.Object.Transactions
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
user :
    SelectionSet decodesTo MonisApp.Object.Users
    -> SelectionSet decodesTo MonisApp.Object.Transactions
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


user_id : SelectionSet String MonisApp.Object.Transactions
user_id =
    Object.selectionForField "String" "user_id" [] Decode.string
