-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.Transactions_max_fields exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


account_id : SelectionSet (Maybe MonisApp.ScalarCodecs.Uuid) MonisApp.Object.Transactions_max_fields
account_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "account_id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


amount : SelectionSet (Maybe Int) MonisApp.Object.Transactions_max_fields
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


category_id : SelectionSet (Maybe MonisApp.ScalarCodecs.Uuid) MonisApp.Object.Transactions_max_fields
category_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "category_id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


comment : SelectionSet (Maybe String) MonisApp.Object.Transactions_max_fields
comment =
    Object.selectionForField "(Maybe String)" "comment" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet (Maybe MonisApp.ScalarCodecs.Timestamptz) MonisApp.Object.Transactions_max_fields
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


date : SelectionSet (Maybe MonisApp.ScalarCodecs.Timestamptz) MonisApp.Object.Transactions_max_fields
date =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "date" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe MonisApp.ScalarCodecs.Uuid) MonisApp.Object.Transactions_max_fields
id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


operation : SelectionSet (Maybe String) MonisApp.Object.Transactions_max_fields
operation =
    Object.selectionForField "(Maybe String)" "operation" [] (Decode.string |> Decode.nullable)


payee : SelectionSet (Maybe String) MonisApp.Object.Transactions_max_fields
payee =
    Object.selectionForField "(Maybe String)" "payee" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe MonisApp.ScalarCodecs.Timestamptz) MonisApp.Object.Transactions_max_fields
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


user_id : SelectionSet (Maybe String) MonisApp.Object.Transactions_max_fields
user_id =
    Object.selectionForField "(Maybe String)" "user_id" [] (Decode.string |> Decode.nullable)
