-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


email : SelectionSet String MonisApp.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


{-| The ID of an object
-}
id : SelectionSet MonisApp.ScalarCodecs.Id MonisApp.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (MonisApp.ScalarCodecs.codecs |> MonisApp.Scalar.unwrapCodecs |> .codecId |> .decoder)


isActive : SelectionSet Bool MonisApp.Object.User
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


name : SelectionSet String MonisApp.Object.User
name =
    Object.selectionForField "String" "name" [] Decode.string
