-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object.Users exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


active : SelectionSet Bool MonisApp.Object.Users
active =
    Object.selectionForField "Bool" "active" [] Decode.bool


email : SelectionSet String MonisApp.Object.Users
email =
    Object.selectionForField "String" "email" [] Decode.string


id : SelectionSet String MonisApp.Object.Users
id =
    Object.selectionForField "String" "id" [] Decode.string


name : SelectionSet String MonisApp.Object.Users
name =
    Object.selectionForField "String" "name" [] Decode.string
