-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import MonisApp.InputObject
import MonisApp.Interface
import MonisApp.Object
import MonisApp.Scalar
import MonisApp.ScalarCodecs
import MonisApp.Union


type alias CreateAccountRequiredArguments =
    { input : MonisApp.InputObject.CreateAccountInput }


createAccount :
    CreateAccountRequiredArguments
    -> SelectionSet decodesTo MonisApp.Object.CreateAccountPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createAccount requiredArgs object_ =
    Object.selectionForCompositeField "createAccount" [ Argument.required "input" requiredArgs.input MonisApp.InputObject.encodeCreateAccountInput ] object_ (identity >> Decode.nullable)


type alias CreateTransactionRequiredArguments =
    { input : MonisApp.InputObject.CreateTransactionInput }


createTransaction :
    CreateTransactionRequiredArguments
    -> SelectionSet decodesTo MonisApp.Object.CreateTransactionPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createTransaction requiredArgs object_ =
    Object.selectionForCompositeField "createTransaction" [ Argument.required "input" requiredArgs.input MonisApp.InputObject.encodeCreateTransactionInput ] object_ (identity >> Decode.nullable)


type alias DeleteAccountRequiredArguments =
    { input : MonisApp.InputObject.DeleteAccountInput }


deleteAccount :
    DeleteAccountRequiredArguments
    -> SelectionSet decodesTo MonisApp.Object.DeleteAccountPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteAccount requiredArgs object_ =
    Object.selectionForCompositeField "deleteAccount" [ Argument.required "input" requiredArgs.input MonisApp.InputObject.encodeDeleteAccountInput ] object_ (identity >> Decode.nullable)


type alias LoginRequiredArguments =
    { email : String
    , password : String
    }


login :
    LoginRequiredArguments
    -> SelectionSet decodesTo MonisApp.Object.LoginResult
    -> SelectionSet (Maybe decodesTo) RootMutation
login requiredArgs object_ =
    Object.selectionForCompositeField "login" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "password" requiredArgs.password Encode.string ] object_ (identity >> Decode.nullable)


type alias RegisterRequiredArguments =
    { input : MonisApp.InputObject.RegisterInput }


register :
    RegisterRequiredArguments
    -> SelectionSet decodesTo MonisApp.Object.RegisterPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
register requiredArgs object_ =
    Object.selectionForCompositeField "register" [ Argument.required "input" requiredArgs.input MonisApp.InputObject.encodeRegisterInput ] object_ (identity >> Decode.nullable)
