-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object exposing (..)


type Accounts
    = Accounts


type Accounts_aggregate
    = Accounts_aggregate


type Accounts_aggregate_fields
    = Accounts_aggregate_fields


type Accounts_max_fields
    = Accounts_max_fields


type Accounts_min_fields
    = Accounts_min_fields


type Accounts_mutation_response
    = Accounts_mutation_response


type Categories
    = Categories


type Categories_aggregate
    = Categories_aggregate


type Categories_aggregate_fields
    = Categories_aggregate_fields


type Categories_max_fields
    = Categories_max_fields


type Categories_min_fields
    = Categories_min_fields


type Categories_mutation_response
    = Categories_mutation_response


type Transactions
    = Transactions


type Transactions_aggregate
    = Transactions_aggregate


type Transactions_aggregate_fields
    = Transactions_aggregate_fields


type Transactions_avg_fields
    = Transactions_avg_fields


type Transactions_max_fields
    = Transactions_max_fields


type Transactions_min_fields
    = Transactions_min_fields


type Transactions_mutation_response
    = Transactions_mutation_response


type Transactions_stddev_fields
    = Transactions_stddev_fields


type Transactions_stddev_pop_fields
    = Transactions_stddev_pop_fields


type Transactions_stddev_samp_fields
    = Transactions_stddev_samp_fields


type Transactions_sum_fields
    = Transactions_sum_fields


type Transactions_var_pop_fields
    = Transactions_var_pop_fields


type Transactions_var_samp_fields
    = Transactions_var_samp_fields


type Transactions_variance_fields
    = Transactions_variance_fields


type Users
    = Users


type Users_aggregate
    = Users_aggregate


type Users_aggregate_fields
    = Users_aggregate_fields


type Users_max_fields
    = Users_max_fields


type Users_min_fields
    = Users_min_fields


type Users_mutation_response
    = Users_mutation_response
