-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.Object exposing (..)


type Account
    = Account


type Category
    = Category


type CreateAccountPayload
    = CreateAccountPayload


type CreateTransactionPayload
    = CreateTransactionPayload


type DeleteAccountPayload
    = DeleteAccountPayload


type LoginResult
    = LoginResult


type RegisterPayload
    = RegisterPayload


type Transaction
    = Transaction


type User
    = User
