-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import MonisApp.Scalar exposing (defaultCodecs)


type alias Id =
    MonisApp.Scalar.Id


codecs : MonisApp.Scalar.Codecs Id
codecs =
    MonisApp.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
