-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module MonisApp.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import MonisApp.Scalar exposing (defaultCodecs)


type alias Timestamptz =
    MonisApp.Scalar.Timestamptz


type alias Uuid =
    MonisApp.Scalar.Uuid


codecs : MonisApp.Scalar.Codecs Timestamptz Uuid
codecs =
    MonisApp.Scalar.defineCodecs
        { codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
